common:
  fp16: true
  log_format: json
  log_interval: 50
  log_file: /logs_B_512gpus_lr0006.out
  wandb_project: wav2vec2_base_lp

checkpoint:
  save_interval_updates: 500
  keep_interval_updates: 1
  keep_best_checkpoints: 5
  no_epoch_checkpoints: true
  save_dir: /outputs_B_512gpus_lr0006
  load_checkpoint_on_all_dp_ranks: true

task:
  _name: audio_pretraining
  data: /manifest_output
  max_sample_size: 960000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 0
  max_tokens: 2800000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 512
  nprocs_per_node: 8
  distributed_port: 29400
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  # max_update: 25000
  max_update: 37500
  update_freq: [1]
  lr: [0.0006]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 3000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
