common:
  fp16: true
  log_format: json
  log_interval: 50
  log_file: /logs_L_512gpus_lr0004.out
  wandb_project: wav2vec2_large_512gpus

checkpoint:
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  keep_best_checkpoints: 7
  save_dir: /outputs_L_512gpus_lr0004
  load_checkpoint_on_all_dp_ranks: true

task:
  _name: audio_pretraining
  data: /manifest_output
  max_sample_size: 960000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 0
  max_tokens: 1800000
  validate_interval: 1000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 512
  nprocs_per_node: 8
  distributed_port: 29400
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 0]

optimization:
  max_update: 60000
  update_freq: [1]
  lr: [0.0004]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 5000

model:
  _name: wav2vec2
  quantize_targets: true
  extractor_mode: layer_norm
  layer_norm_first: true
  final_dim: 768
  latent_temp: [2.0,0.1,0.999995]
  encoder_layerdrop: 0.2
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  conv_bias: true
  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16
  feature_grad_mult: 1.0
