common:
  fp16: true
  log_format: json
  log_interval: 50
  log_file: /logs_L_full_ft_3e-4.out
  wandb_project: wav2vec2_large_fairseq_ft

checkpoint:
  save_interval: 1
  no_epoch_checkpoints: true
  keep_best_checkpoints: 5
  save_dir: /outputs_B_full_ft_2e-4
  load_checkpoint_on_all_dp_ranks: true
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: /donatespeech_fairseq
  normalize: true
  max_sample_size: 960000000
  min_sample_size: 8000
  labels: ltr

dataset:
  num_workers: 0
  max_tokens: 2400000
  train_subset: train-lp-full
  valid_subset: valid-lp-50s
  skip_invalid_size_inputs_valid_test: false

distributed_training:
  distributed_world_size: 128
  nprocs_per_node: 8
  distributed_port: 29400
  ddp_backend: legacy_ddp

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 5000
  sentence_avg: false
  update_freq: [1]
  lr: [0.0003]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 1250

model:
  _name: wav2vec_ctc
  apply_mask: true
  mask_prob: 0.5
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
